### ISSUE TITLE
Both launchers at the same time...

### ISSUE THREAD

**Issue by iadegesso** [LaurentTreguier/gnome-optirun#1]
Some applications runs only with primusrun and other ones only using optirun: the solution... two launchers available at the same time...

I added a few lines of code to obtain my goal... so, I will share the modified file.

Iade

[extension.js.zip](https://github.com/LaurentTreguier/gnome-optirun/files/143201/extension.js.zip)

**Comment by LaurentTreguier** [comment]
It looks alright, I've commited the file and uploaded the extension to extensions.gnome.org. This new version should be "officially" released not too long from now, once the extension has been reviewed. Thanks for the upgrade !
